version: '3.9'

name: bot

services:
  bot:
    image: bot
    build:
      context: .
      target: production
    ports:
      # Should match with .env BOT_SERVER_PORT
      - 80:80
    env_file:
      - .env
    restart: always
    networks:
      - bot

networks:
  bot:
